services:
    db:
        image: postgres:16-alpine
        container_name: postgres_db
        restart: always
        environment:
            - POSTGRES_DB=telegram-re-db
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        volumes:
            - postgres_data:/var/lib/postgresql/data

    redis_db:
        image: redis:7.2.4-alpine
        container_name: redis_db
        restart: always
        ports:
            - "6379:6379"
        volumes:
            - redis_data:/data

volumes:
    postgres_data:
    redis_data:
