version: "3.8"

services:
    frontend:
        build: ./frontend
        container_name: telegram-re-frontend
        environment:
            - PORT=3000
            - HOST=0.0.0.0
        ports:
            - "3000:3000"
        volumes:
            - ./frontend:/app
            - /app/node_modules
