version: "3.8"

services:
    db:
        image: postgres:16-alpine
        container_name: postgres_db
        restart: unless-stopped
        environment:
            - POSTGRES_DB=telegram-re-db
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        volumes:
            - postgres_data:/var/lib/postgresql/data

    backend:
        build: ./backend
        container_name: telegram-re-backend
        env_file:
            - ./backend/.env
        ports:
            - "8000:8000"
        volumes:
            - ./backend:/code
        depends_on:
            - db

    frontend:
        build: ./frontend
        container_name: telegram-re-frontend
        env_file:
            - ./frontend/.env
        ports:
            - "3000:3000"
        volumes:
            - ./frontend:/app
            - /app/node_modules

volumes:
    postgres_data:
