[tool.poetry]
name = "backend"
version = "0.1.0"
description = ""
authors = ["tokitou-san <tokitousan2005@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
django = "^4.2.6"
psycopg = "^3.1.12"
pillow = "^10.0.1"
django-dynamic-filenames = "^1.3.2"
django-cleanup = "^8.0.0"
python-dotenv = "^1.0.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
